SET(CMAKE_SYSTEM_NAME Linux)  
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)

SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I/root/workspace/mgba-miyoo")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I/root/workspace/mgba-miyoo")

SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -L$ENV{FIN_BIN_DIR}/lib -L../src")
SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -L$ENV{FIN_BIN_DIR}/lib -L../src")

SET(SDL2_INCLUDE_DIRS /mnt/SDCARD/App/MGBA/include/SDL2)
SET(SDL2_LIBRARIES /mnt/SDCARD/App/MGBA/lib/libSDL2-2.0.so.0)

